--------------------------------------------------------
-- Archivo creado  - domingo-julio-24-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ADMINISTRADOR
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."ADMINISTRADOR" 
   (	"IDPERSONA" VARCHAR2(10 BYTE), 
	"FECHAULTIMOACCESO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENCUESTA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."ENCUESTA" 
   (	"IDENCUESTA" NUMBER, 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"DESCRIPCION" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENCUESTAPERSONA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" 
   (	"IDENCUESTAPERSONAL" NUMBER, 
	"IDENCUESTA" NUMBER, 
	"IDPERSONA" VARCHAR2(10 BYTE), 
	"FECHACREACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OPCION
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."OPCION" 
   (	"IDOPCION" NUMBER, 
	"IDPREGUNTA" NUMBER, 
	"NOMBRE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PACIENTE
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PACIENTE" 
   (	"IDPERSONA" VARCHAR2(10 BYTE), 
	"CONTACTOEMERGENCIA" VARCHAR2(10 BYTE), 
	"FECHANACIMIENTO" DATE, 
	"NIVELACADEMICO" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PERSONA" 
   (	"IDPERSONA" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(60 BYTE), 
	"DIRECCION" VARCHAR2(60 BYTE), 
	"TELEFONO" VARCHAR2(10 BYTE), 
	"SEXO" VARCHAR2(1 BYTE), 
	"CLAVE" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PREGUNTA" 
   (	"IDPREGUNTA" NUMBER, 
	"IDENCUESTA" NUMBER, 
	"TITULO" VARCHAR2(200 BYTE), 
	"ESOPCIONAL" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTABOLEANA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PREGUNTABOLEANA" 
   (	"IDPREGUNTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTAFECHA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PREGUNTAFECHA" 
   (	"IDPREGUNTA" NUMBER, 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTAHORA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PREGUNTAHORA" 
   (	"IDPREGUNTA" NUMBER, 
	"TIEMPO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTANUMERICA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" 
   (	"IDPREGUNTA" NUMBER, 
	"LIMITEINFERIOR" NUMBER, 
	"LIMITESUPERIOR" NUMBER, 
	"INTERVALODISCRETO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTAOPCIONMULTIPLE
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" 
   (	"IDPREGUNTA" NUMBER, 
	"NUMMAXSELECCIONES" NUMBER, 
	"TIENECAMPOADICIONAL" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTATEXTUAL
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PREGUNTATEXTUAL" 
   (	"IDPREGUNTA" NUMBER, 
	"NUMMAXCARACTERES" NUMBER, 
	"PATRON" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTA" 
   (	"IDRESPUESTA" NUMBER, 
	"IDENCUESTAPERSONA" NUMBER, 
	"IDPREGUNTA" NUMBER, 
	"IDENCUESTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAPREGUNTABOLEANA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTABOLEANA" 
   (	"IDRESPUESTA" NUMBER, 
	"RESPUESTA" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAPREGUNTAFECHA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAFECHA" 
   (	"IDRESPUESTA" NUMBER, 
	"RESPUESTA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAPREGUNTAHORA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA" 
   (	"IDRESPUESTA" NUMBER, 
	"RESPUESTAS" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAPREGUNTANUMERICA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTANUMERICA" 
   (	"IDRESPUESTA" NUMBER, 
	"RESPUESTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAPREGUNTAOPCIONAL
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" 
   (	"IDRESPUESTA" NUMBER, 
	"IDOPCION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAPREGUNTATEXTUAL
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTATEXTUAL" 
   (	"IDRESPUESTA" NUMBER, 
	"RESPUESTA" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CONTROLPACIENTES.ADMINISTRADOR
SET DEFINE OFF;
Insert into CONTROLPACIENTES.ADMINISTRADOR (IDPERSONA,FECHAULTIMOACCESO) values ('0105036024',to_date('25/12/2016','DD/MM/RRRR'));
REM INSERTING into CONTROLPACIENTES.ENCUESTA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.ENCUESTAPERSONA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.OPCION
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PACIENTE
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PERSONA
SET DEFINE OFF;
Insert into CONTROLPACIENTES.PERSONA (IDPERSONA,NOMBRE,DIRECCION,TELEFONO,SEXO,CLAVE) values ('0105036024','Juan','Don bosco','4030255','M','1234');
Insert into CONTROLPACIENTES.PERSONA (IDPERSONA,NOMBRE,DIRECCION,TELEFONO,SEXO,CLAVE) values ('0105036032','Juan','Don bosco','4030255','M','1234');
REM INSERTING into CONTROLPACIENTES.PREGUNTA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PREGUNTABOLEANA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PREGUNTAFECHA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PREGUNTAHORA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PREGUNTANUMERICA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PREGUNTAOPCIONMULTIPLE
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PREGUNTATEXTUAL
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTAPREGUNTABOLEANA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTAPREGUNTAFECHA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTAPREGUNTAHORA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTAPREGUNTANUMERICA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTAPREGUNTAOPCIONAL
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTAPREGUNTATEXTUAL
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index RESPUESTAPREGUNTABOLEANA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTAPREGUNTABOLEANA_PK" ON "CONTROLPACIENTES"."RESPUESTAPREGUNTABOLEANA" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PACIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PACIENTE_PK" ON "CONTROLPACIENTES"."PACIENTE" ("IDPERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENCUESTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."ENCUESTA_PK" ON "CONTROLPACIENTES"."ENCUESTA" ("IDENCUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENCUESTAPERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."ENCUESTAPERSONA_PK" ON "CONTROLPACIENTES"."ENCUESTAPERSONA" ("IDENCUESTAPERSONAL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OPCIONES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."OPCIONES_PK" ON "CONTROLPACIENTES"."OPCION" ("IDOPCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREGUNTAOPCIONMULTIPLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE_PK" ON "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" ("IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREGUNTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PREGUNTA_PK" ON "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTAPREGUNTATEXTUAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTAPREGUNTATEXTUAL_PK" ON "CONTROLPACIENTES"."RESPUESTAPREGUNTATEXTUAL" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREGUNTATEXTUAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PREGUNTATEXTUAL_PK" ON "CONTROLPACIENTES"."PREGUNTATEXTUAL" ("IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTAPREGUNTANUMERICA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTAPREGUNTANUMERICA_PK" ON "CONTROLPACIENTES"."RESPUESTAPREGUNTANUMERICA" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PERSONA_PK" ON "CONTROLPACIENTES"."PERSONA" ("IDPERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADMINISTRADOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."ADMINISTRADOR_PK" ON "CONTROLPACIENTES"."ADMINISTRADOR" ("IDPERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREGUNTANUMERICA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PREGUNTANUMERICA_PK" ON "CONTROLPACIENTES"."PREGUNTANUMERICA" ("IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTA_PK" ON "CONTROLPACIENTES"."RESPUESTA" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTAPREGUNTAFECHA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTAPREGUNTAFECHA_PK" ON "CONTROLPACIENTES"."RESPUESTAPREGUNTAFECHA" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTAPREGUNTAHORA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA_PK" ON "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTAPREGUNTAOPCIONAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL_PK" ON "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table OPCION
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."OPCION" ADD CONSTRAINT "OPCIONES_PK" PRIMARY KEY ("IDOPCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."OPCION" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."OPCION" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."OPCION" MODIFY ("IDOPCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTAHORA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAHORA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PACIENTE
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PACIENTE" ADD CONSTRAINT "PACIENTE_PK" PRIMARY KEY ("IDPERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PACIENTE" MODIFY ("NIVELACADEMICO" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PACIENTE" MODIFY ("FECHANACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PACIENTE" MODIFY ("CONTACTOEMERGENCIA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PACIENTE" MODIFY ("IDPERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTABOLEANA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTABOLEANA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAPREGUNTANUMERICA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTANUMERICA" ADD CONSTRAINT "RESPUESTAPREGUNTANUMERICA_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTANUMERICA" MODIFY ("RESPUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTANUMERICA" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENCUESTA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."ENCUESTA" ADD CONSTRAINT "ENCUESTA_PK" PRIMARY KEY ("IDENCUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAPREGUNTAHORA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA" ADD CONSTRAINT "RESPUESTAPREGUNTAHORA_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA" MODIFY ("RESPUESTAS" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTA" ADD CONSTRAINT "PREGUNTA_PK" PRIMARY KEY ("IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTA" MODIFY ("ESOPCIONAL" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTA" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PERSONA" ADD CONSTRAINT "PERSONA_PK" PRIMARY KEY ("IDPERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PERSONA" MODIFY ("CLAVE" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PERSONA" MODIFY ("SEXO" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PERSONA" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PERSONA" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PERSONA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PERSONA" MODIFY ("IDPERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTANUMERICA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" ADD CONSTRAINT "PREGUNTANUMERICA_PK" PRIMARY KEY ("IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" MODIFY ("INTERVALODISCRETO" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" MODIFY ("LIMITESUPERIOR" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" MODIFY ("LIMITEINFERIOR" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAPREGUNTATEXTUAL
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTATEXTUAL" ADD CONSTRAINT "RESPUESTAPREGUNTATEXTUAL_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTATEXTUAL" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMINISTRADOR
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."ADMINISTRADOR" ADD CONSTRAINT "ADMINISTRADOR_PK" PRIMARY KEY ("IDPERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."ADMINISTRADOR" MODIFY ("FECHAULTIMOACCESO" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."ADMINISTRADOR" MODIFY ("IDPERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" ADD CONSTRAINT "RESPUESTA_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" MODIFY ("IDENCUESTAPERSONA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENCUESTAPERSONA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" ADD CONSTRAINT "ENCUESTAPERSONA_PK" PRIMARY KEY ("IDENCUESTAPERSONAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" MODIFY ("FECHACREACION" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" MODIFY ("IDPERSONA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" MODIFY ("IDENCUESTAPERSONAL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTAFECHA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAFECHA" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAFECHA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTAOPCIONMULTIPLE
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" ADD CONSTRAINT "PREGUNTAOPCIONMULTIPLE_PK" PRIMARY KEY ("IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" MODIFY ("TIENECAMPOADICIONAL" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" MODIFY ("NUMMAXSELECCIONES" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAPREGUNTAFECHA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAFECHA" ADD CONSTRAINT "RESPUESTAPREGUNTAFECHA_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAFECHA" MODIFY ("RESPUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAFECHA" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTATEXTUAL
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTATEXTUAL" ADD CONSTRAINT "PREGUNTATEXTUAL_PK" PRIMARY KEY ("IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTATEXTUAL" MODIFY ("PATRON" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTATEXTUAL" MODIFY ("NUMMAXCARACTERES" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTATEXTUAL" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAPREGUNTAOPCIONAL
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" ADD CONSTRAINT "RESPUESTAPREGUNTAOPCIONAL_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" MODIFY ("IDOPCION" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAPREGUNTABOLEANA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTABOLEANA" ADD CONSTRAINT "RESPUESTAPREGUNTABOLEANA_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTABOLEANA" MODIFY ("RESPUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTABOLEANA" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADMINISTRADOR
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."ADMINISTRADOR" ADD CONSTRAINT "CLAVE_APERSONA_FK" FOREIGN KEY ("IDPERSONA")
	  REFERENCES "CONTROLPACIENTES"."PERSONA" ("IDPERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENCUESTAPERSONA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" ADD CONSTRAINT "CLAVE_ENCUESTAOPCIONAL2_FK" FOREIGN KEY ("IDPERSONA")
	  REFERENCES "CONTROLPACIENTES"."PERSONA" ("IDPERSONA") ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" ADD CONSTRAINT "CLAVE_ENCUESTAPERSONA1_FK" FOREIGN KEY ("IDENCUESTA")
	  REFERENCES "CONTROLPACIENTES"."ENCUESTA" ("IDENCUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OPCION
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."OPCION" ADD CONSTRAINT "CALVE_OPCIONESPREGUNTA_FK" FOREIGN KEY ("IDPREGUNTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" ("IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PACIENTE
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PACIENTE" ADD CONSTRAINT "CLAVE_PACIENTE_FK" FOREIGN KEY ("IDPERSONA")
	  REFERENCES "CONTROLPACIENTES"."PERSONA" ("IDPERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTA" ADD CONSTRAINT "CLAVE_FK" FOREIGN KEY ("IDENCUESTA")
	  REFERENCES "CONTROLPACIENTES"."ENCUESTA" ("IDENCUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTABOLEANA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTABOLEANA" ADD CONSTRAINT "CLAVEPREGUNTABOLEANA_FK" FOREIGN KEY ("IDPREGUNTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTAFECHA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAFECHA" ADD CONSTRAINT "CLAVE_PREGUNTAFECHA_FK" FOREIGN KEY ("IDPREGUNTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTAHORA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAHORA" ADD CONSTRAINT "CLAVE_PREGGUNTAHORA_FK" FOREIGN KEY ("IDPREGUNTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTANUMERICA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" ADD CONSTRAINT "CLAVEPREGUNTANUMERICA_FK" FOREIGN KEY ("IDPREGUNTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTAOPCIONMULTIPLE
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" ADD CONSTRAINT "CLAVE_PREGUNTAOPCIONAL_FK" FOREIGN KEY ("IDPREGUNTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTATEXTUAL
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTATEXTUAL" ADD CONSTRAINT "CLAVEPREGUNTATEXTUAL_FK" FOREIGN KEY ("IDPREGUNTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" ADD CONSTRAINT "CLAVE_RESPUESTAENCUESTA" FOREIGN KEY ("IDENCUESTA")
	  REFERENCES "CONTROLPACIENTES"."ENCUESTA" ("IDENCUESTA") ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" ADD CONSTRAINT "CLAVE_RESPUESTAENCUESTA_FK" FOREIGN KEY ("IDENCUESTAPERSONA")
	  REFERENCES "CONTROLPACIENTES"."ENCUESTAPERSONA" ("IDENCUESTAPERSONAL") ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" ADD CONSTRAINT "CLAVE_RESPUESTAPREGUNTA_FK" FOREIGN KEY ("IDPREGUNTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAPREGUNTABOLEANA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTABOLEANA" ADD CONSTRAINT "CLAVE_RESPUESTAPREGUNTABOL_FK" FOREIGN KEY ("IDRESPUESTA")
	  REFERENCES "CONTROLPACIENTES"."RESPUESTA" ("IDRESPUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAPREGUNTAFECHA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAFECHA" ADD CONSTRAINT "CLAVE_PREGUNTAHORA_FK" FOREIGN KEY ("IDRESPUESTA")
	  REFERENCES "CONTROLPACIENTES"."RESPUESTA" ("IDRESPUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAPREGUNTAHORA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA" ADD CONSTRAINT "CLAVE_RESPUESTAHORA_FK" FOREIGN KEY ("IDRESPUESTA")
	  REFERENCES "CONTROLPACIENTES"."RESPUESTA" ("IDRESPUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAPREGUNTANUMERICA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTANUMERICA" ADD CONSTRAINT "CLAVE_RESPUESTAPRNUM_FK" FOREIGN KEY ("IDRESPUESTA")
	  REFERENCES "CONTROLPACIENTES"."RESPUESTA" ("IDRESPUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAPREGUNTAOPCIONAL
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" ADD CONSTRAINT "CLAVE_RESPUESTASOPCIONALES1_FK" FOREIGN KEY ("IDOPCION")
	  REFERENCES "CONTROLPACIENTES"."OPCION" ("IDOPCION") ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" ADD CONSTRAINT "CLAVE_RESPUOPCIO2_FK" FOREIGN KEY ("IDRESPUESTA")
	  REFERENCES "CONTROLPACIENTES"."RESPUESTA" ("IDRESPUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAPREGUNTATEXTUAL
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTATEXTUAL" ADD CONSTRAINT "CLAVE_RESPUESTATEXTUAL_FK" FOREIGN KEY ("IDRESPUESTA")
	  REFERENCES "CONTROLPACIENTES"."RESPUESTA" ("IDRESPUESTA") ENABLE;
