package com.trivialbox.controlpacientes.gui;

import com.trivialbox.controlpacientes.srv.encuestaSrv.EncuestaSrv;
import javax.swing.JOptionPane;



public class VentanaEncabezadoAdministrador extends javax.swing.JInternalFrame {
    EncuestaSrv encuestaSrv;
    public int actualizar = 0;
    /**
     * Creates new form VentanaEncabezadoAdministrador
     */
    public VentanaEncabezadoAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        entryNombreEncuesta = new javax.swing.JTextField();
        btnCrearEncuesta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(458, 416));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("lISTA DE ENCUESTAS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 24));

        entryNombreEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entryNombreEncuestaActionPerformed(evt);
            }
        });
        getContentPane().add(entryNombreEncuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 309, -1));

        btnCrearEncuesta.setText("Agregar");
        btnCrearEncuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearEncuestaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearEncuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 111, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/trivialbox/controlpacientes/imagenes/fondoInicioPregunta.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entryNombreEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entryNombreEncuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_entryNombreEncuestaActionPerformed

    private void btnCrearEncuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearEncuestaActionPerformed
        encuestaSrv = new EncuestaSrv();
        encuestaSrv.agregarEncuesta(entryNombreEncuesta.getText(), "null");
        //agregarNuevaEncuesta(entryNombreEncuesta.getText());
        this.update(this.getGraphics());
        this.entryNombreEncuesta.setText(null);
        JOptionPane.showMessageDialog(rootPane, "Encuesta Agreada, vaya a Herramientas y actualize");


    }//GEN-LAST:event_btnCrearEncuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEncabezadoAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEncabezadoAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEncabezadoAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEncabezadoAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEncabezadoAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearEncuesta;
    private javax.swing.JTextField entryNombreEncuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
