package com.trivialbox.controlpacientes.gui;

import java.awt.Color;
import java.awt.Dimension;
import java.util.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javafx.scene.layout.Border;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;


/**
 *
 * @author root
 */
public class VentanaAdministrador extends javax.swing.JFrame {
    List<JPanel> listaEncuestas = new ArrayList<>();
    /**
     * Creates new form VentanaAdministrador
     */
    public VentanaAdministrador() {
        initComponents();
        crearEncuetas();
    }
    void crearEncuetas(){
        
        List<String> encuestas = new ArrayList<>();
        encuestas.add("Hola mudno como estas por alla");
        encuestas.add("dos");
        encuestas.add("dfdf");
        encuestas.add("ghos");
        encuestas.add("fghjjhj");
        encuestas.add("sd");
        encuestas.add("jjjjjj");
        Dimension dimension = new Dimension(150, 30);
        int posX = 5, posY = 5;
        
         for(int a = 0; a < 7;a++){
            JPanel panel = new JPanel();
            panel.setBorder(BorderFactory.createCompoundBorder(BorderFactory.createLineBorder(Color.getHSBColor(122, 55, 65)),
                                                                BorderFactory.createEmptyBorder(10, 15, 5, 15)));
            JLabel label1;
            if(encuestas.get(a).length() >= 10){
                label1 = new JLabel(encuestas.get(a).substring(0, 10)+"..");
            }else {
                label1 = new JLabel(encuestas.get(a));
            }
            label1.setToolTipText(encuestas.get(a));
            JLabel label = new JLabel(encuestas.get(a));
            panel.setBounds(posX, posY, 100, 70);
            if(posX >300){
                posX = 5;
                posY = posY + 80;
            }else{
                posX= posX+110;
            }
            
            this.add(panel);
            JButton boton = new JButton("Editar");
            
            boton.setSize(dimension);


            boton.addActionListener((java.awt.event.ActionEvent evt) -> {
                actionPerformedqq(evt,label.getText());
            });

            label.setBounds(a, a, 100, 30);
            panel.add(label1);
            panel.add(boton);
        }
        
    }
    public void actionPerformedqq(ActionEvent e, String nom) {
        System.out.println(nom);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 422, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
