--------------------------------------------------------
-- Archivo creado  - lunes-julio-25-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ADMINISTRADOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CONTROLPACIENTES"."ADMINISTRADOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ENCUESTAPERSONA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CONTROLPACIENTES"."ENCUESTAPERSONA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ENCUESTAPREGUNTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CONTROLPACIENTES"."ENCUESTAPREGUNTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ENCUESTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CONTROLPACIENTES"."ENCUESTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence OPCION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CONTROLPACIENTES"."OPCION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PREGUNTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CONTROLPACIENTES"."PREGUNTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RESPUESTA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CONTROLPACIENTES"."RESPUESTA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ADMINISTRADOR
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."ADMINISTRADOR" 
   (	"IDPERSONA" VARCHAR2(10 BYTE), 
	"FECHAULTIMOACCESO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table BITACORA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."BITACORA" 
   (	"IDPERONA" VARCHAR2(10 BYTE), 
	"RESPUESTA" VARCHAR2(1000 BYTE), 
	"FECHAINGRESO" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENCUESTA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."ENCUESTA" 
   (	"IDENCUESTA" NUMBER, 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"DESCRIPCION" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ENCUESTAPERSONA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" 
   (	"IDENCUESTAPERSONA" NUMBER, 
	"IDENCUESTA" NUMBER, 
	"IDPERSONA" VARCHAR2(10 BYTE), 
	"FECHAASIGNACION" DATE, 
	"FECHARESPUESTA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table OPCION
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."OPCION" 
   (	"IDOPCION" NUMBER, 
	"IDENCUESTA" NUMBER, 
	"IDPREGUNTA" NUMBER, 
	"NOMBRE" VARCHAR2(200 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PACIENTE
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PACIENTE" 
   (	"IDPERSONA" VARCHAR2(10 BYTE), 
	"CONTACTOEMERGENCIA" VARCHAR2(10 BYTE), 
	"FECHANACIMIENTO" DATE, 
	"NIVELACADEMICO" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PEGUNTABOOLEANA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PEGUNTABOOLEANA" 
   (	"IDENCUESTA" NUMBER, 
	"IDPREGUNTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PERSONA" 
   (	"IDPERSONA" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(60 BYTE), 
	"DIRECCION" VARCHAR2(60 BYTE), 
	"TELEFONO" VARCHAR2(10 BYTE), 
	"SEXO" VARCHAR2(1 BYTE), 
	"CLAVE" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PREGUNTA" 
   (	"IDPREGUNTA" NUMBER, 
	"IDENCUESTA" NUMBER, 
	"TITULO" VARCHAR2(200 BYTE), 
	"ESOPCIONAL" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTAFECHA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PREGUNTAFECHA" 
   (	"IDENCUESTA" NUMBER, 
	"IDPREGUNTA" NUMBER, 
	"FECHA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTAHORA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PREGUNTAHORA" 
   (	"IDENCUESTA" NUMBER, 
	"IDPREGUNTA" NUMBER, 
	"TIEMPO" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTANUMERICA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" 
   (	"IDENCUESTA" NUMBER, 
	"IDPREGUNTA" VARCHAR2(20 BYTE), 
	"LIMITEINFERIOR" NUMBER, 
	"LIMITESUPERIOR" NUMBER, 
	"INTERVALODISCRETO" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTAOPCIONMULTIPLE
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" 
   (	"IDENCUESTA" NUMBER, 
	"IDPREGUNTA" NUMBER, 
	"NUMMAXSELECCIONES" NUMBER, 
	"TIENECAMPOADICIONAL" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PREGUNTATEXTUAL
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."PREGUNTATEXTUAL" 
   (	"IDENCUESTA" NUMBER, 
	"IDPREGUNTA" NUMBER, 
	"NUMMAXCARACTERES" NUMBER, 
	"PATRON" VARCHAR2(60 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTA" 
   (	"IDRESPUESTA" NUMBER, 
	"IDENCUESTAPERSONA" NUMBER, 
	"IDENCUESTA" NUMBER, 
	"IDPREGUNTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAPREGUNTABOOLEANA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTABOOLEANA" 
   (	"IDRESPUESTA" NUMBER, 
	"RESPUESTA" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAPREGUNTAFECHA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAFECHA" 
   (	"IDRESPUESTA" NUMBER, 
	"RESPUESTA" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAPREGUNTAHORA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA" 
   (	"IDRESPUESTA" NUMBER, 
	"RESPUESTAS" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAPREGUNTANUMERICA
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTANUMERICA" 
   (	"IDRESPUESTA" NUMBER, 
	"RESPUESTA" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAPREGUNTAOPCIONAL
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" 
   (	"IDRESPUESTA" NUMBER, 
	"IDOPCION" NUMBER, 
	"IDENCUESTA" NUMBER, 
	"IDPREGUNTA" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RESPUESTAPREGUNTATEXTUAL
--------------------------------------------------------

  CREATE TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTATEXTUAL" 
   (	"IDRESPUESTA" NUMBER, 
	"RESPUESTA" VARCHAR2(1000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into CONTROLPACIENTES.ADMINISTRADOR
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.BITACORA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.ENCUESTA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.ENCUESTAPERSONA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.OPCION
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PACIENTE
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PEGUNTABOOLEANA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PERSONA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PREGUNTA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PREGUNTAFECHA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PREGUNTAHORA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PREGUNTANUMERICA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PREGUNTAOPCIONMULTIPLE
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.PREGUNTATEXTUAL
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTAPREGUNTABOOLEANA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTAPREGUNTAFECHA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTAPREGUNTAHORA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTAPREGUNTANUMERICA
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTAPREGUNTAOPCIONAL
SET DEFINE OFF;
REM INSERTING into CONTROLPACIENTES.RESPUESTAPREGUNTATEXTUAL
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index RESPUESTAPREGUNTABOLEANA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTAPREGUNTABOLEANA_PK" ON "CONTROLPACIENTES"."RESPUESTAPREGUNTABOOLEANA" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREGUNTABOLEANA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PREGUNTABOLEANA_PK" ON "CONTROLPACIENTES"."PEGUNTABOOLEANA" ("IDENCUESTA", "IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PACIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PACIENTE_PK" ON "CONTROLPACIENTES"."PACIENTE" ("IDPERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENCUESTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."ENCUESTA_PK" ON "CONTROLPACIENTES"."ENCUESTA" ("IDENCUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENCUESTAPERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."ENCUESTAPERSONA_PK" ON "CONTROLPACIENTES"."ENCUESTAPERSONA" ("IDENCUESTAPERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREGUNTAOPCIONMULTIPLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE_PK" ON "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" ("IDENCUESTA", "IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREGUNTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PREGUNTA_PK" ON "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA", "IDENCUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTAPREGUNTATEXTUAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTAPREGUNTATEXTUAL_PK" ON "CONTROLPACIENTES"."RESPUESTAPREGUNTATEXTUAL" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index BITACORA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."BITACORA_PK" ON "CONTROLPACIENTES"."BITACORA" ("IDPERONA", "FECHAINGRESO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREGUNTAFECHA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PREGUNTAFECHA_PK" ON "CONTROLPACIENTES"."PREGUNTAFECHA" ("IDENCUESTA", "IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREGUNTATEXTUAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PREGUNTATEXTUAL_PK" ON "CONTROLPACIENTES"."PREGUNTATEXTUAL" ("IDENCUESTA", "IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTAPREGUNTANUMERICA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTAPREGUNTANUMERICA_PK" ON "CONTROLPACIENTES"."RESPUESTAPREGUNTANUMERICA" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PERSONA_PK" ON "CONTROLPACIENTES"."PERSONA" ("IDPERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index OPCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."OPCION_PK" ON "CONTROLPACIENTES"."OPCION" ("IDOPCION", "IDENCUESTA", "IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ADMINISTRADOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."ADMINISTRADOR_PK" ON "CONTROLPACIENTES"."ADMINISTRADOR" ("IDPERSONA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREGUNTANUMERICA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PREGUNTANUMERICA_PK" ON "CONTROLPACIENTES"."PREGUNTANUMERICA" ("IDENCUESTA", "IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTA_PK" ON "CONTROLPACIENTES"."RESPUESTA" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTAPREGUNTAFECHA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTAPREGUNTAFECHA_PK" ON "CONTROLPACIENTES"."RESPUESTAPREGUNTAFECHA" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ENCUESTA_UK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."ENCUESTA_UK1" ON "CONTROLPACIENTES"."ENCUESTA" ("NOMBRE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTAPREGUNTAHORA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA_PK" ON "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RESPUESTAPREGUNTAOPCIONAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL_PK" ON "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" ("IDRESPUESTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PREGUNTAHORA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CONTROLPACIENTES"."PREGUNTAHORA_PK" ON "CONTROLPACIENTES"."PREGUNTAHORA" ("IDENCUESTA", "IDPREGUNTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table OPCION
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."OPCION" ADD CONSTRAINT "OPCION_PK" PRIMARY KEY ("IDOPCION", "IDENCUESTA", "IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."OPCION" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."OPCION" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."OPCION" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."OPCION" MODIFY ("IDOPCION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAPREGUNTABOOLEANA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTABOOLEANA" MODIFY ("RESPUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTABOOLEANA" ADD CONSTRAINT "RESPUESTAPREGUNTABOLEANA_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTABOOLEANA" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTAHORA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAHORA" ADD CONSTRAINT "PREGUNTAHORA_PK" PRIMARY KEY ("IDENCUESTA", "IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAHORA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAHORA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PACIENTE
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PACIENTE" ADD CONSTRAINT "PACIENTE_PK" PRIMARY KEY ("IDPERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PACIENTE" MODIFY ("FECHANACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PACIENTE" MODIFY ("CONTACTOEMERGENCIA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PACIENTE" MODIFY ("IDPERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAPREGUNTANUMERICA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTANUMERICA" ADD CONSTRAINT "RESPUESTAPREGUNTANUMERICA_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTANUMERICA" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENCUESTA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."ENCUESTA" ADD CONSTRAINT "ENCUESTA_PK" PRIMARY KEY ("IDENCUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTA" ADD CONSTRAINT "ENCUESTA_UK1" UNIQUE ("NOMBRE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RESPUESTAPREGUNTAHORA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA" ADD CONSTRAINT "RESPUESTAPREGUNTAHORA_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA" MODIFY ("RESPUESTAS" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BITACORA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."BITACORA" ADD CONSTRAINT "BITACORA_PK" PRIMARY KEY ("IDPERONA", "FECHAINGRESO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."BITACORA" MODIFY ("FECHAINGRESO" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."BITACORA" MODIFY ("RESPUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."BITACORA" MODIFY ("IDPERONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTA" ADD CONSTRAINT "PREGUNTA_PK" PRIMARY KEY ("IDPREGUNTA", "IDENCUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTA" MODIFY ("ESOPCIONAL" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTA" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PERSONA" ADD CONSTRAINT "PERSONA_PK" PRIMARY KEY ("IDPERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PERSONA" MODIFY ("CLAVE" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PERSONA" MODIFY ("SEXO" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PERSONA" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PERSONA" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PERSONA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PERSONA" MODIFY ("IDPERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTANUMERICA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" ADD CONSTRAINT "PREGUNTANUMERICA_PK" PRIMARY KEY ("IDENCUESTA", "IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" MODIFY ("INTERVALODISCRETO" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" MODIFY ("LIMITESUPERIOR" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" MODIFY ("LIMITEINFERIOR" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAPREGUNTATEXTUAL
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTATEXTUAL" ADD CONSTRAINT "RESPUESTAPREGUNTATEXTUAL_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTATEXTUAL" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PEGUNTABOOLEANA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PEGUNTABOOLEANA" ADD CONSTRAINT "PREGUNTABOLEANA_PK" PRIMARY KEY ("IDENCUESTA", "IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PEGUNTABOOLEANA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PEGUNTABOOLEANA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ADMINISTRADOR
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."ADMINISTRADOR" ADD CONSTRAINT "ADMINISTRADOR_PK" PRIMARY KEY ("IDPERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."ADMINISTRADOR" MODIFY ("IDPERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" ADD CONSTRAINT "RESPUESTA_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" MODIFY ("IDENCUESTAPERSONA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ENCUESTAPERSONA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" ADD CONSTRAINT "ENCUESTAPERSONA_PK" PRIMARY KEY ("IDENCUESTAPERSONA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" MODIFY ("FECHAASIGNACION" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" MODIFY ("IDPERSONA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" MODIFY ("IDENCUESTAPERSONA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTAFECHA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAFECHA" ADD CONSTRAINT "PREGUNTAFECHA_PK" PRIMARY KEY ("IDENCUESTA", "IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAFECHA" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAFECHA" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTAOPCIONMULTIPLE
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" ADD CONSTRAINT "PREGUNTAOPCIONMULTIPLE_PK" PRIMARY KEY ("IDENCUESTA", "IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" MODIFY ("TIENECAMPOADICIONAL" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" MODIFY ("NUMMAXSELECCIONES" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAPREGUNTAFECHA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAFECHA" ADD CONSTRAINT "RESPUESTAPREGUNTAFECHA_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAFECHA" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PREGUNTATEXTUAL
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTATEXTUAL" ADD CONSTRAINT "PREGUNTATEXTUAL_PK" PRIMARY KEY ("IDENCUESTA", "IDPREGUNTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTATEXTUAL" MODIFY ("NUMMAXCARACTERES" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTATEXTUAL" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."PREGUNTATEXTUAL" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESPUESTAPREGUNTAOPCIONAL
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" ADD CONSTRAINT "RESPUESTAPREGUNTAOPCIONAL_PK" PRIMARY KEY ("IDRESPUESTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" MODIFY ("IDOPCION" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" MODIFY ("IDRESPUESTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" MODIFY ("IDPREGUNTA" NOT NULL ENABLE);
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" MODIFY ("IDENCUESTA" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ADMINISTRADOR
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."ADMINISTRADOR" ADD CONSTRAINT "ADMINISTRADOR_FK1" FOREIGN KEY ("IDPERSONA")
	  REFERENCES "CONTROLPACIENTES"."PERSONA" ("IDPERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BITACORA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."BITACORA" ADD CONSTRAINT "BITACORA_FK1" FOREIGN KEY ("IDPERONA")
	  REFERENCES "CONTROLPACIENTES"."PERSONA" ("IDPERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ENCUESTAPERSONA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" ADD CONSTRAINT "ENCUESTAPERSONA_FK1" FOREIGN KEY ("IDENCUESTA")
	  REFERENCES "CONTROLPACIENTES"."ENCUESTA" ("IDENCUESTA") ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."ENCUESTAPERSONA" ADD CONSTRAINT "ENCUESTAPERSONA_FK2" FOREIGN KEY ("IDPERSONA")
	  REFERENCES "CONTROLPACIENTES"."PERSONA" ("IDPERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OPCION
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."OPCION" ADD CONSTRAINT "OPCION_FK1" FOREIGN KEY ("IDENCUESTA", "IDPREGUNTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" ("IDENCUESTA", "IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PACIENTE
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PACIENTE" ADD CONSTRAINT "PACIENTE_FK1" FOREIGN KEY ("IDPERSONA")
	  REFERENCES "CONTROLPACIENTES"."PERSONA" ("IDPERSONA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PEGUNTABOOLEANA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PEGUNTABOOLEANA" ADD CONSTRAINT "PREGUNTABOLEANA_FK1" FOREIGN KEY ("IDPREGUNTA", "IDENCUESTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA", "IDENCUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTA" ADD CONSTRAINT "PREGUNTA_FK1" FOREIGN KEY ("IDENCUESTA")
	  REFERENCES "CONTROLPACIENTES"."ENCUESTA" ("IDENCUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTAFECHA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAFECHA" ADD CONSTRAINT "PREGUNTAFECHA_FK1" FOREIGN KEY ("IDPREGUNTA", "IDENCUESTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA", "IDENCUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTAHORA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAHORA" ADD CONSTRAINT "PREGUNTAHORA_FK1" FOREIGN KEY ("IDPREGUNTA", "IDENCUESTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA", "IDENCUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTANUMERICA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTANUMERICA" ADD CONSTRAINT "PREGUNTANUMERICA_FK1" FOREIGN KEY ("IDENCUESTA", "LIMITEINFERIOR")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA", "IDENCUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTAOPCIONMULTIPLE
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTAOPCIONMULTIPLE" ADD CONSTRAINT "PREGUNTAOPCIONMULTIPLE_FK1" FOREIGN KEY ("IDPREGUNTA", "IDENCUESTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA", "IDENCUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PREGUNTATEXTUAL
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."PREGUNTATEXTUAL" ADD CONSTRAINT "PREGUNTATEXTUAL_FK1" FOREIGN KEY ("IDPREGUNTA", "IDENCUESTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA", "IDENCUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" ADD CONSTRAINT "RESPUESTA_FK1" FOREIGN KEY ("IDENCUESTAPERSONA")
	  REFERENCES "CONTROLPACIENTES"."ENCUESTAPERSONA" ("IDENCUESTAPERSONA") ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" ADD CONSTRAINT "RESPUESTA_FK2" FOREIGN KEY ("IDENCUESTA")
	  REFERENCES "CONTROLPACIENTES"."ENCUESTA" ("IDENCUESTA") ENABLE;
  ALTER TABLE "CONTROLPACIENTES"."RESPUESTA" ADD CONSTRAINT "RESPUESTA_FK3" FOREIGN KEY ("IDPREGUNTA", "IDENCUESTA")
	  REFERENCES "CONTROLPACIENTES"."PREGUNTA" ("IDPREGUNTA", "IDENCUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAPREGUNTABOOLEANA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTABOOLEANA" ADD CONSTRAINT "RESPUESTAPREGUNTABOLEANA_FK1" FOREIGN KEY ("IDRESPUESTA")
	  REFERENCES "CONTROLPACIENTES"."RESPUESTA" ("IDRESPUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAPREGUNTAFECHA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAFECHA" ADD CONSTRAINT "RESPUESTAPREGUNTAFECHA_FK1" FOREIGN KEY ("IDRESPUESTA")
	  REFERENCES "CONTROLPACIENTES"."RESPUESTA" ("IDRESPUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAPREGUNTAHORA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAHORA" ADD CONSTRAINT "RESPUESTAPREGUNTAHORA_FK1" FOREIGN KEY ("IDRESPUESTA")
	  REFERENCES "CONTROLPACIENTES"."RESPUESTA" ("IDRESPUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAPREGUNTANUMERICA
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTANUMERICA" ADD CONSTRAINT "RESPUESTAPREGUNTANUMERICA_FK1" FOREIGN KEY ("IDRESPUESTA")
	  REFERENCES "CONTROLPACIENTES"."RESPUESTA" ("IDRESPUESTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAPREGUNTAOPCIONAL
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTAOPCIONAL" ADD CONSTRAINT "RESPUESTAPREGUNTAOPCIONAL_FK1" FOREIGN KEY ("IDOPCION", "IDENCUESTA", "IDRESPUESTA")
	  REFERENCES "CONTROLPACIENTES"."OPCION" ("IDOPCION", "IDENCUESTA", "IDPREGUNTA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESPUESTAPREGUNTATEXTUAL
--------------------------------------------------------

  ALTER TABLE "CONTROLPACIENTES"."RESPUESTAPREGUNTATEXTUAL" ADD CONSTRAINT "RESPUESTAPREGUNTATEXTUAL_FK1" FOREIGN KEY ("IDRESPUESTA")
	  REFERENCES "CONTROLPACIENTES"."RESPUESTA" ("IDRESPUESTA") ENABLE;
--------------------------------------------------------
--  DDL for Trigger INCREMENTO_ENCUESTA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CONTROLPACIENTES"."INCREMENTO_ENCUESTA" 
   before insert on "CONTROLPACIENTES"."ENCUESTA" 
   for each row 
begin  
   if inserting then 
      if :NEW."IDENCUESTA" is null then 
         select ENCUESTA_SEQ.nextval into :NEW."IDENCUESTA" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "CONTROLPACIENTES"."INCREMENTO_ENCUESTA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INCREMENTO_ENCUESTAPERSONA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CONTROLPACIENTES"."INCREMENTO_ENCUESTAPERSONA" 
   before insert on "CONTROLPACIENTES"."ENCUESTAPERSONA" 
   for each row 
begin  
   if inserting then 
      if :NEW."IDENCUESTAPERSONA" is null then 
         select ENCUESTAPERSONA_SEQ.nextval into :NEW."IDENCUESTAPERSONA" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "CONTROLPACIENTES"."INCREMENTO_ENCUESTAPERSONA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INCREMENTO_OPCION
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CONTROLPACIENTES"."INCREMENTO_OPCION" 
   before insert on "CONTROLPACIENTES"."OPCION" 
   for each row 
begin  
   if inserting then 
      if :NEW."IDOPCION" is null then 
         select OPCION_SEQ.nextval into :NEW."IDOPCION" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "CONTROLPACIENTES"."INCREMENTO_OPCION" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INCREMENTO_PREGUNTA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CONTROLPACIENTES"."INCREMENTO_PREGUNTA" 
   before insert on "CONTROLPACIENTES"."PREGUNTA" 
   for each row 
begin  
   if inserting then 
      if :NEW."IDPREGUNTA" is null then 
         select PREGUNTA_SEQ.nextval into :NEW."IDPREGUNTA" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "CONTROLPACIENTES"."INCREMENTO_PREGUNTA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INCREMENTO_RESPUESTA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CONTROLPACIENTES"."INCREMENTO_RESPUESTA" 
   before insert on "CONTROLPACIENTES"."RESPUESTA" 
   for each row 
begin  
   if inserting then 
      if :NEW."IDRESPUESTA" is null then 
         select RESPUESTA_SEQ.nextval into :NEW."IDRESPUESTA" from dual; 
      end if; 
   end if; 
end;

/
ALTER TRIGGER "CONTROLPACIENTES"."INCREMENTO_RESPUESTA" ENABLE;
--------------------------------------------------------
--  DDL for Trigger INSERTARBITACORA
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "CONTROLPACIENTES"."INSERTARBITACORA" 
AFTER INSERT ON RESPUESTAPREGUNTABOOLEANA 
FOR EACH ROW
BEGIN
  INSERT INTO BITACORA VALUES('0',:NEW.RESPUESTA,SYSDATE);    
  NULL;
END;
/
ALTER TRIGGER "CONTROLPACIENTES"."INSERTARBITACORA" ENABLE;
--------------------------------------------------------
--  DDL for Procedure PA_AUTOR_SUMAYPROMEDIO
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CONTROLPACIENTES"."PA_AUTOR_SUMAYPROMEDIO" 

  @suma decimal(6,2) output,
  @promedio decimal(6,2) output
  as 
   select idrespuesta,respuesta,
   from respuestapreguntanumerica
  select @suma=sum(respuesta)
   from respuestapreguntanumerica
  select @promedio=avg(respuesta)
   from respuestapreguntanumerica

 declare @s decimal(6,2), @p decimal(6,2)
 execute pa_autor_sumaypromedio 'Richard Bach', @s output, @p output
 select @s as total, @p as promedio;

/
--------------------------------------------------------
--  DDL for Procedure PROMEDIOPREGUNTANUMERICA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CONTROLPACIENTES"."PROMEDIOPREGUNTANUMERICA" AS 
promedio number(6,2);
BEGIN
  SELECT AVG(RESPUESTA) into promedio FROM RESPUESTAPREGUNTANUMERICA;
  return;
END PROMEDIOPREGUNTANUMERICA;

/
--------------------------------------------------------
--  DDL for Procedure SUMATORIASPREGUNTANUMERICA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "CONTROLPACIENTES"."SUMATORIASPREGUNTANUMERICA" 
as 
sumatoria number;
begin
  select sum(respuesta) into sumatoria from RESPUESTAPREGUNTANUMERICA;
  return;
end sumatoriaspreguntanumerica;

/
